//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecruitmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecruitmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RecruitmentResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Name.
        /// </summary>
        internal static string ApplicantNameText {
            get {
                return ResourceManager.GetString("ApplicantNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ApplicantName}.
        /// </summary>
        internal static string ApplicantNameValue {
            get {
                return ResourceManager.GetString("ApplicantNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Date.
        /// </summary>
        internal static string DeadlineText {
            get {
                return ResourceManager.GetString("DeadlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Deadline}.
        /// </summary>
        internal static string DeadlineValue {
            get {
                return ResourceManager.GetString("DeadlineValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Link.
        /// </summary>
        internal static string PositionLinkText {
            get {
                return ResourceManager.GetString("PositionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PositionLink}.
        /// </summary>
        internal static string PositionLinkValue {
            get {
                return ResourceManager.GetString("PositionLinkValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Title.
        /// </summary>
        internal static string PositionTitleText {
            get {
                return ResourceManager.GetString("PositionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PositionTitle}.
        /// </summary>
        internal static string PositionTitleValue {
            get {
                return ResourceManager.GetString("PositionTitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Department.
        /// </summary>
        internal static string PrimaryDepartmentText {
            get {
                return ResourceManager.GetString("PrimaryDepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PrimaryDepartment}.
        /// </summary>
        internal static string PrimaryDepartmentValue {
            get {
                return ResourceManager.GetString("PrimaryDepartmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Admin Email.
        /// </summary>
        internal static string RecruitmentAdminEmailText {
            get {
                return ResourceManager.GetString("RecruitmentAdminEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RecruitmentAdminEmail}.
        /// </summary>
        internal static string RecruitmentAdminEmailValue {
            get {
                return ResourceManager.GetString("RecruitmentAdminEmailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Admin Name.
        /// </summary>
        internal static string RecruitmentAdminNameText {
            get {
                return ResourceManager.GetString("RecruitmentAdminNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RecruitmentAdminName}.
        /// </summary>
        internal static string RecruitmentAdminNameValue {
            get {
                return ResourceManager.GetString("RecruitmentAdminNameValue", resourceCulture);
            }
        }
    }
}
