// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using CAESDO.Recruitment.Core.Domain;

namespace CAESDO.Recruitment.Test
{
    /// <summary>
    ///This is a test class for CAESDO.Recruitment.Core.Domain.Applicant and is intended
    ///to contain all CAESDO.Recruitment.Core.Domain.Applicant Unit Tests
    ///</summary>
    [TestClass()]
    public class ApplicantTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        public static int ExisitingApplicantID = 4;

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Applicant ()
        ///</summary>
        public void ConstructorTest()
        {
            Applicant target = new Applicant();

            target = NHibernateHelper.daoFactory.GetApplicantDao().GetById(ExisitingApplicantID, false);

            Assert.IsNotNull(target);
            Assert.AreEqual(target.ID, ExisitingApplicantID);
        }

        /// <summary>
        ///A test for CreatedBy
        ///</summary>
        public void CreatedByTest()
        {
            Applicant target = new Applicant();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.CreatedBy = val;


            Assert.AreEqual(val, target.CreatedBy, "CAESDO.Recruitment.Core.Domain.Applicant.CreatedBy was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Email
        ///</summary>
        public void EmailTest()
        {
            Applicant target = new Applicant();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Email = val;


            Assert.AreEqual(val, target.Email, "CAESDO.Recruitment.Core.Domain.Applicant.Email was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Fill (int, bool)
        ///</summary>
        public void FillTest()
        {
            Applicant target = new Applicant();

            int AccountID = 0; // TODO: Initialize to an appropriate value

            bool LoadProfile = false; // TODO: Initialize to an appropriate value

            target.Fill(AccountID, LoadProfile);

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for IsActive
        ///</summary>
        public void IsActiveTest()
        {
            Applicant target = new Applicant();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.IsActive = val;


            Assert.AreEqual(val, target.IsActive, "CAESDO.Recruitment.Core.Domain.Applicant.IsActive was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for MainProfile
        ///</summary>
        public void MainProfileTest()
        {
            Applicant target = new Applicant();

            Profile val = null; // TODO: Assign to an appropriate value for the property


            Assert.AreEqual(val, target.MainProfile, "CAESDO.Recruitment.Core.Domain.Applicant.MainProfile was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Profiles
        ///</summary>
        public void ProfilesTest()
        {
            Applicant target = new Applicant();

            System.Collections.Generic.IList<CAESDO.Recruitment.Core.Domain.Profile> val = null; // TODO: Assign to an appropriate value for the property

            target.Profiles = val;


            Assert.AreEqual(val, target.Profiles, "CAESDO.Recruitment.Core.Domain.Applicant.Profiles was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
