// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using CAESDO.Recruitment.Core.Domain;
namespace Recruitment.Tests
{
    /// <summary>
    ///This is a test class for CAESDO.Recruitment.Core.Domain.CurrentPosition and is intended
    ///to contain all CAESDO.Recruitment.Core.Domain.CurrentPosition Unit Tests
    ///</summary>
    [TestClass()]
    public class CurrentPositionTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Address1
        ///</summary>
        [TestMethod()]
        public void Address1Test()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Address1 = val;


            Assert.AreEqual(val, target.Address1, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Address1 was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Address2
        ///</summary>
        [TestMethod()]
        public void Address2Test()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Address2 = val;


            Assert.AreEqual(val, target.Address2, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Address2 was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for ApplicationStepType
        ///</summary>
        [TestMethod()]
        public void ApplicationStepTypeTest()
        {
            CurrentPosition target = new CurrentPosition();

            ApplicationStepType val = ApplicationStepType.CurrentPosition; // TODO: Assign to an appropriate value for the property

            target.ApplicationStepType = val;


            Assert.AreEqual(val, target.ApplicationStepType, "CAESDO.Recruitment.Core.Domain.CurrentPosition.ApplicationStepType was not set co" +
                    "rrectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for AssociatedApplication
        ///</summary>
        [TestMethod()]
        public void AssociatedApplicationTest()
        {
            CurrentPosition target = new CurrentPosition();

            Application val = null; // TODO: Assign to an appropriate value for the property

            target.AssociatedApplication = val;


            Assert.AreEqual(val, target.AssociatedApplication, "CAESDO.Recruitment.Core.Domain.CurrentPosition.AssociatedApplication was not set " +
                    "correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for City
        ///</summary>
        [TestMethod()]
        public void CityTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.City = val;


            Assert.AreEqual(val, target.City, "CAESDO.Recruitment.Core.Domain.CurrentPosition.City was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Complete
        ///</summary>
        [TestMethod()]
        public void CompleteTest()
        {
            CurrentPosition target = new CurrentPosition();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.Complete = val;


            Assert.AreEqual(val, target.Complete, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Complete was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Country
        ///</summary>
        [TestMethod()]
        public void CountryTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Country = val;


            Assert.AreEqual(val, target.Country, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Country was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for CurrentPosition ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            CurrentPosition target = new CurrentPosition();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for Department
        ///</summary>
        [TestMethod()]
        public void DepartmentTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Department = val;


            Assert.AreEqual(val, target.Department, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Department was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Fill ()
        ///</summary>
        [TestMethod()]
        public void FillTest()
        {
            CurrentPosition target = new CurrentPosition();

            target.Fill();

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for Institution
        ///</summary>
        [TestMethod()]
        public void InstitutionTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Institution = val;


            Assert.AreEqual(val, target.Institution, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Institution was not set correctly." +
                    "");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for isComplete ()
        ///</summary>
        [TestMethod()]
        public void isCompleteTest()
        {
            CurrentPosition target = new CurrentPosition();

            bool expected = false;
            bool actual;

            actual = target.isComplete();

            Assert.AreEqual(expected, actual, "CAESDO.Recruitment.Core.Domain.CurrentPosition.isComplete did not return the expe" +
                    "cted value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Save ()
        ///</summary>
        [TestMethod()]
        public void SaveTest()
        {
            CurrentPosition target = new CurrentPosition();

            target.Save();

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for State
        ///</summary>
        [TestMethod()]
        public void StateTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.State = val;


            Assert.AreEqual(val, target.State, "CAESDO.Recruitment.Core.Domain.CurrentPosition.State was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Title
        ///</summary>
        [TestMethod()]
        public void TitleTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Title = val;


            Assert.AreEqual(val, target.Title, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Title was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Zip
        ///</summary>
        [TestMethod()]
        public void ZipTest()
        {
            CurrentPosition target = new CurrentPosition();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Zip = val;


            Assert.AreEqual(val, target.Zip, "CAESDO.Recruitment.Core.Domain.CurrentPosition.Zip was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
